/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('bias').del()
  await knex('bias').insert([
    {
      name: 'Gawker',
      bias_rating: 'LEFT',
      factual_reporting: 'MIXED',
      country: 'MIXED',
      media_type: 'USA',
      popularity: 'MOSTLY FREE',
      mbfc_credibility_rating: 'MEDIUM CREDIBILITY',
    },
    {
      name: 'NBC News',
      bias_rating: 'LEFT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA',
      popularity: 'MOSTLY FREE',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'Houston Chronicle',
      bias_rating: 'LEFT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA (44/180 Press Freedom)',
      popularity: 'Newspaper',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'Yahoo News',
      bias_rating: 'LEFT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA',
      popularity: 'MOSTLY FREE',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'HuffPost',
      bias_rating: '',
      factual_reporting: '',
      country: '',
      media_type: '',
      popularity: '',
      mbfc_credibility_rating: '',
    },
    {
      name: 'The Bulwark',
      bias_rating: 'RIGHT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA (44/180 Press Freedom)',
      popularity: 'Website',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'CNN',
      bias_rating: 'LEFT',
      factual_reporting: 'MIXED',
      country: '',
      media_type: 'MIXED',
      popularity: 'USA',
      mbfc_credibility_rating: 'MEDIUM CREDIBILITY',
    },
    {
      name: 'Washington Post',
      bias_rating: 'LEFT-CENTER',
      factual_reporting: 'MOSTLY FACTUAL',
      country: 'MOSTLY FACTUAL',
      media_type: 'USA',
      popularity: 'MOSTLY FREE',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'HotAir',
      bias_rating: '',
      factual_reporting: '',
      country: '',
      media_type: '',
      popularity: '',
      mbfc_credibility_rating: '',
    },
    {
      name: 'ABC News',
      bias_rating: 'LEFT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA',
      popularity: 'MOSTLY FREE',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'Vicky Ward Investigates',
      bias_rating: '',
      factual_reporting: '',
      country: '',
      media_type: '',
      popularity: '',
      mbfc_credibility_rating: '',
    },
    {
      name: 'Politico',
      bias_rating: 'LEFT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA',
      popularity: 'MOSTLY FREE',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'Commentary Magazine',
      bias_rating: 'MOSTLY FACTUAL',
      factual_reporting: 'Left vs. Right Bias: How we rate the bias of media sources',
      country: 'USA 45/180',
      media_type: 'History',
      popularity: 'Funded by / Ownership',
      mbfc_credibility_rating: 'Your Support is Essential',
    },
    {
      name: 'New Yorker',
      bias_rating: 'LEFT',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA (45/180 Press Freedom)',
      popularity: 'Magazine',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'The Dispatch',
      bias_rating: 'RIGHT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA (44/180 Press Freedom)',
      popularity: 'Website',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
    {
      name: 'The White House',
      bias_rating: 'Left vs. Right Bias: How we rate the bias of media sources',
      factual_reporting: '',
      country: '',
      media_type: '',
      popularity: '',
      mbfc_credibility_rating: '',
    },
    {
      name: 'Presidentti',
      bias_rating: '',
      factual_reporting: '',
      country: '',
      media_type: '',
      popularity: '',
      mbfc_credibility_rating: '',
    },
    {
      name: 'New York Times',
      bias_rating: 'LEFT-CENTER',
      factual_reporting: 'HIGH',
      country: 'HIGH',
      media_type: 'USA',
      popularity: 'MOSTLY FREE',
      mbfc_credibility_rating: 'HIGH CREDIBILITY',
    },
  ])
}
